server:
  port: 8080

#zuul:
#  routes:
#    nacos-demo: /h/**

spring:
  application:
    name: gateway-t1
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: proxy
          uri: lb://nacos-demo
          predicates:
            - Path=/h/**
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


name: kkkk
